version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
    labels:
      - improvement

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
    labels:
      - improvement

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
    labels:
      - improvement
