version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - improvement

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - improvement

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - improvement
