[tool.ruff]
select = [
    "F",        # pyflakes
    "W",        # pycodestyle warnings
    "E",        # pycodestyle errors
    "C90",      # mccabe
    "I",        # isort
    "N",        # pep8-naming
    "D",        # pydocstyle
    "UP",       # pyupgrade
    "ASYNC",    # flake8-async
    "S",        # flake8-bandit
    "B",        # flake8-bugbear
    "COM",      # flake8-commas
    "C4",       # flake8-comprehensions
    "RET",      # flake8-return
    "SIM",      # flake8-simplify
    "TCH",      # flake8-type-checking
    "ARG",      # flake8-unused-arguments
    "PTH",      # flake8-use-pathlib
    "PGH",      # pygrep-hooks
    "PL",       # Pylint
    "RUF",      # Ruff-specific rules
]

ignore = [
    # Mising docstrings
    # These should be enabled in the future, but for now it's just too much at once
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",

    # Wacky docstring defaults
    "D203",
    "D213",

    # Insane suggestion that pathlib.Path.open() should be prefered over open()
    "PTH123"
]

line-length = 120

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # Unused imports in __init__.py are fine
