manifest_version = 1

[module]
id = "settings"
name = "Settings"
description = "Commands to help get, set and modify the settings API directly from Discord"
version = "0.1.0"
license = "GNU LGPLv3"
authors = ["ThatOtherAndrew"]
