name: Auto Assign

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  assign_members:
    name: Assign Members
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: author
          reviewers: ThatOtherAndrew

  assign_project:
    name: Assign Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          github-token: ${{ secrets.ACTIONS_ADD_TO_PROJECT }}
          project-url: https://github.com/orgs/Breadcord/projects/1
